name: Deploy to GitHub Pages

于:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build and Export
        env:
          # 读取 Secrets 里的 ID，如果没有配置 Secrets，会自动读取 blog.config.js 里的
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          npm run build
          npm run export
          touch out/.nojekyll  # <---【关键修改】就是这行！添加 .nojekyll 文件防止 _next 文件夹被忽略

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
